[tool.briefcase]
project_name = "hackathon-app"
bundle = "com.example"
version = "0.0.1"
url = "http://3.37.124.193:8502/"
license = "BSD license"
author = 'Ohwooju'
author_email = "wj9183@gmail.com"

[tool.briefcase.app.hackathon-app]
formal_name = "hackathon-app"
description = "hackathon-app"
icon = "src/hackathon_app/resources/hackathon-app"
sources = ['src/hackathon_app']
requires = []


[tool.briefcase.app.hackathon-app.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.hackathon-app.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.hackathon-app.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.hackathon-app.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.hackathon-app.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
